"use client";
import { useMemo, useState } from "react";
import { Footer, Header } from "./SiteChrome";
import { useI18n } from "./I18nProvider";
const amounts=[1000,5000,10000,25000,50000];
const bank={bank:"JazzCash",name:"Markaz ul huda",iban:"PK37 JCMA 2606 9234 8659 6339"};
export default function DonatePage(){const {t}=useI18n();const [amount,setAmount]=useState(5000),[type,setType]=useState<"once"|"monthly">("once"),[name,setName]=useState(""),[toast,setToast]=useState(false);
 const impact=amount>=100000?"imp5":amount>=25000?"imp4":amount>=10000?"imp3":amount>=5000?"imp2":"imp1";
 const wa=useMemo(()=>{const msg=`Assalamu alaikum! ${name?`I am ${name}. `:""}I would like to donate PKR ${amount.toLocaleString()} (${type==="monthly"?"monthly":"one-time"}) to Markaz Ali ul Murtaza via JazzCash (Markaz ul huda). JazakAllahu khairan.`;return `https://wa.me/923014592661?text=${encodeURIComponent(msg)}`},[amount,type,name]);
 const copy=(v:string)=>{navigator.clipboard?.writeText(v);setToast(true);setTimeout(()=>setToast(false),1800)};
 return <><Header dark active="donate"/><main><section className="dn-hero"><div className="reveal"><p className="kicker gold">{t("dn_kicker")}</p><h1>{t("dn_title")}</h1><p className="dn-hero-sub">{t("dn_sub")}</p><div className="dn-verse"><p className="dn-verse-ar" lang="ar" dir="rtl">﴿ مَّثَلُ الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ ﴾</p><p className="dn-verse-tr">{t("dn_verse")}<span className="verse-ref">{t("dn_verse_ref")}</span></p></div><div className="hero-ctas"><a href="#donate" className="btn btn-light">{t("nav_donate")}</a><a href="https://wa.me/923014592661" className="btn btn-outline-light">WhatsApp</a></div></div></section>
 <section className="dn-main" id="donate"><div className="dn-grid"><div className="dn-box reveal"><div className="seg"><button className={type==="once"?"active":""} onClick={()=>setType("once")}>{t("dn_once")}</button><button className={type==="monthly"?"active":""} onClick={()=>setType("monthly")}>{t("dn_monthly")}</button></div><p className="dn-label">{t("dn_amount")}</p><div className="chips">{amounts.map(a=><button key={a} className={`chip ${amount===a?"active":""}`} onClick={()=>setAmount(a)}>{a.toLocaleString()}</button>)}</div><div className="dn-range-row"><input type="range" min="500" max="200000" step="500" value={Math.min(amount,200000)} onChange={e=>setAmount(+e.target.value)}/><input id="amtInput" type="number" min="100" value={amount} onChange={e=>setAmount(Math.max(100,+e.target.value))}/></div><div className="dn-impact"><div className="native-icon">♡</div><div><p className="dn-impact-label">{t("dn_impact")}</p><p>{t(impact)} {type==="monthly"&&t("dn_each_month")}</p></div></div><p className="dn-label">{t("dn_bank_title")}</p><div className="dn-bank">{[[t("dn_bank"),bank.bank],[t("dn_acc_name"),bank.name],[t("dn_iban_l"),bank.iban]].map(([k,v])=><div className="dn-row" key={k}><span className="dn-k">{k}</span><b dir={k===t("dn_iban_l")?"ltr":undefined}>{v}</b><button className="hact" onClick={()=>copy(v)}>▣</button></div>)}</div><button className="btn btn-ghost btn-copyall" onClick={()=>copy(`${bank.bank}\n${bank.name}\nIBAN: ${bank.iban}`)}>{t("dn_copy_all")}</button><input className="dn-name" value={name} onChange={e=>setName(e.target.value)} placeholder={t("dn_your_name")}/><a className="btn btn-wa btn-send" href={wa}>◉ {t("dn_send")}</a></div>
 <div className="dn-side"><div className="dn-card reveal"><h3>{t("dn_where")}</h3>{[["dn_w_sch",40],["dn_w_teach",35],["dn_w_plat",15],["dn_w_admin",10]].map(([k,w])=><div className="bar" key={k}><div className="bar-top"><span>{t(k as string)}</span><b>{w}%</b></div><div className="bar-fill" style={{width:`${w}%`}}/></div>)}</div><div className="dn-card reveal"><h3>{t("dn_services")}</h3><div className="dn-services">{[1,2,3,4].map(n=><a href="/#programs" key={n}>✦ <span>{t(`p${n}_title`)}</span></a>)}<a href="/hadith">▣ <span>{t("nav_hadith")}</span></a><a href="/#enroll">◎ <span>{t("f4_t")}</span></a></div></div></div></div></section>
 <section className="dn-had"><p className="dn-had-ar" lang="ar" dir="rtl">«الصَّدَقَةُ لَا تَنْقُصُ الْمَالَ»</p><p className="dn-had-tr">{t("dn_had")}<span className="verse-ref">{t("dn_had_ref")}</span></p></section></main><div className={`toast ${toast?"show":""}`}>{t("dn_copied")}</div><Footer/></>}
