"use client";
import { useEffect, useState } from "react";
import { useI18n } from "./I18nProvider";

const unsupported = new Set(["ks"]);
function chunks(text:string){const sentences=text.match(/[^.!?…۔؟\n]+[.!?…۔؟]*/g)||[text];const out:string[]=[];let current="";for(const sentence of sentences){if((current+sentence).length>470){if(current)out.push(current);current=sentence}else current+=sentence}if(current)out.push(current);return out}
async function google(text:string,lang:string){const url=`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${encodeURIComponent(lang)}&dt=t&q=${encodeURIComponent(text)}`;const result=await fetch(url).then(r=>{if(!r.ok)throw new Error("translation unavailable");return r.json()});return (result[0]||[]).map((part:string[])=>part?.[0]||"").join("")}
async function myMemory(text:string,lang:string){const translated:string[]=[];for(const chunk of chunks(text)){const url=`https://api.mymemory.translated.net/get?q=${encodeURIComponent(chunk)}&langpair=${encodeURIComponent(`en|${lang}`)}`;const result=await fetch(url).then(r=>{if(!r.ok)throw new Error("translation unavailable");return r.json()});const value=result?.responseData?.translatedText;if(!value)throw new Error("empty translation");translated.push(value)}return translated.join(" ")}
export default function HadithTranslation({text,id}:{text:string;id:number}){const {t,lang,languages,order}=useI18n();const [selected,setSelected]=useState(lang),[output,setOutput]=useState(text),[loading,setLoading]=useState(false);useEffect(()=>setSelected(lang),[lang]);useEffect(()=>{let cancelled=false;if(selected==="en"||unsupported.has(selected)){setOutput(text);return}const key=`hadith-translation:${id}:${selected}`;const cached=localStorage.getItem(key);if(cached){setOutput(cached);return}setLoading(true);google(text,selected).catch(()=>myMemory(text,selected)).then(value=>{if(!cancelled){setOutput(value);localStorage.setItem(key,value)}}).catch(()=>!cancelled&&setOutput(text)).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[selected,text,id]);const rtl=["ar","ur","fa","ps","sd","ks"].includes(selected);return <section className="seo-translation"><label className="tr-lang"><span>{t("hd_trans_lang")}</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{order.map(code=><option key={code} value={code}>{languages[code].name}{unsupported.has(code)?" (English fallback)":""}</option>)}</select></label><div className="had-tr"><p className={`had-text ${loading?"skel":""}`} dir={rtl?"rtl":"ltr"} lang={selected}>{loading?t("lib_loading"):output}</p><p className="had-tr-meta">{languages[selected].name}{selected!=="en"&&!unsupported.has(selected)?` · ${t("hd_mt_tag")}`:""}</p></div></section>}
