"use client";
import Link from "next/link";
import { Footer, Header } from "./SiteChrome";
import { useI18n } from "./I18nProvider";

const programs=[
 {n:1,ar:"حِفْظُ الْقُرْآنِ",colors:["#10B981","#0E7490"]},
 {n:2,ar:"التَّجْوِيدُ",colors:["#7C3AED","#DB2777"]},
 {n:3,ar:"القِرَاءَاتُ السَّبْعُ وَالْعَشْرُ",colors:["#1E3A8A","#0EA5E9"]},
 {n:4,ar:"التَّفْسِيرُ وَالتَّرْجُمَةُ",colors:["#EA580C","#BE185D"]}
];
const features=["f1","f2","f3","f4","f5","f6"];
const stats=[[12000,"stats_students"],[45,"stats_countries"],[300,"stats_teachers"],[15,"stats_years"]] as const;
function ProgramArt({p}:{p:typeof programs[number]}){return <svg className="poster" viewBox="0 0 800 600" role="img"><defs><linearGradient id={`g${p.n}`} x2="1" y2="1"><stop stopColor={p.colors[0]}/><stop offset="1" stopColor={p.colors[1]}/></linearGradient><pattern id={`pat${p.n}`} width="80" height="80" patternUnits="userSpaceOnUse"><path d="M40 8l8 24 24 8-24 8-8 24-8-24-24-8 24-8z" fill="none" stroke="#fff" strokeOpacity=".12"/></pattern></defs><rect width="800" height="600" rx="24" fill={`url(#g${p.n})`}/><rect width="800" height="600" rx="24" fill={`url(#pat${p.n})`}/><text x="400" y="150" textAnchor="middle" fontFamily="Amiri,serif" fontSize="62" fontWeight="700" fill="#FDE68A">{p.ar}</text><g transform="translate(400 360)"><path d="M-180-45C-95-78-25-78 0-55V80C-30 50-100 50-180 84Z" fill="#FFF7E6"/><path d="M180-45C95-78 25-78 0-55V80C30 50 100 50 180 84Z" fill="#FBEFD4"/><path d="M0-55V80" stroke="#D9A62E" strokeWidth="5"/><path d="M-145-18C-90-38-45-38-20-28M-145 12C-90-8-45-8-20 2M145-18C90-38 45-38 20-28M145 12C90-8 45-8 20 2" stroke="#CBB27E" strokeWidth="4" fill="none"/></g><circle cx="155" cy="220" r="13" fill="#F0C75E"/><circle cx="650" cy="420" r="12" fill="#fff" opacity=".7"/></svg>}
export default function HomePage(){const {t}=useI18n();return <><Header/><main>
<section className="hero" id="home"><div className="hero-inner reveal"><p className="hero-badge"><span className="dot"/>{t("hero_badge")}</p><h1>{t("hero_title")}</h1><p className="hero-sub">{t("hero_sub")}</p><div className="hero-ctas"><a href="#enroll" className="btn btn-primary">{t("hero_cta1")}</a><a href="#programs" className="btn btn-ghost link-more">{t("hero_cta2")}</a></div></div><div className="hero-art reveal"><img src="/images/hero-art.svg" alt="Al-Qur’an al-Karim"/></div></section>
<section className="verse"><p className="verse-ar" lang="ar" dir="rtl">﴿ وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا ﴾</p><p className="verse-trans">{t("verse_trans")}<span className="verse-ref">{t("verse_ref")}</span></p></section>
<section className="programs" id="programs"><div className="section-head reveal"><p className="kicker">{t("programs_kicker")}</p><h2>{t("programs_title")}</h2><p className="section-sub">{t("programs_sub")}</p></div>{programs.map((p,i)=><div className={`feature-row reveal ${i%2?"flip":""}`} key={p.n}><div className="feature-copy"><h3>{t(`p${p.n}_title`)}</h3><p>{t(`p${p.n}_desc`)}</p><ul className="checks">{[1,2,3].map(b=><li key={b}>{t(`p${p.n}_b${b}`)}</li>)}</ul><a href="#enroll" className="link-more">{t("programs_more")}</a></div><div className="feature-media"><ProgramArt p={p}/></div></div>)}</section>
<section className="qurras" id="qurras"><div className="section-head reveal"><p className="kicker">{t("qurras_kicker")}</p><h2>{t("qurras_title")}</h2><p className="section-sub">{t("qurras_sub")}</p></div><div className="qurras-grid">{[["Qari Ahmed Azizi","qari-azizi-thumb.jpg","head_role","+92 301 4592661","923014592661"],["Qari Abdur Rahman Al Afin","qari-abdurrahman-thumb.jpg","qari_role","+92 316 8724692","923168724692"]].map(q=><article className="qari reveal" key={q[0]}><div className="qari-video"><img src={`/images/${q[1]}`} alt={q[0]} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div className="qari-info"><h3>{q[0]}</h3><p className="qari-role">{t(q[2])}</p><a className="qari-phone" href={`tel:+${q[4]}`}>{q[3]}</a><div className="qari-actions"><a className="btn btn-call" href={`tel:+${q[4]}`}>{t("call_label")}</a><a className="btn btn-wa" href={`https://wa.me/${q[4]}`}>WhatsApp</a></div></div></article>)}</div></section>
<section className="features" id="features"><div className="section-head reveal"><p className="kicker">{t("features_kicker")}</p><h2>{t("features_title")}</h2></div><div className="feature-grid">{features.map((f,i)=><article className="card reveal" key={f}><div className="native-icon">{["◉","✦","◷","◇","▣","◎"][i]}</div><h3>{t(`${f}_t`)}</h3><p>{t(`${f}_d`)}</p></article>)}</div></section>
<section className="stats"><div className="stats-grid">{stats.map(([n,k])=><div className="stat reveal" key={k}><span className="stat-num">{new Intl.NumberFormat().format(n)}+</span><span className="stat-label">{t(k)}</span></div>)}</div></section>
<section className="method" id="method"><div className="section-head reveal"><p className="kicker">{t("method_kicker")}</p><h2>{t("method_title")}</h2></div><div className="steps">{[1,2,3].map(n=><div className="step reveal" key={n}><span className="step-num">{n}</span><h3>{t(`m${n}_t`)}</h3><p>{t(`m${n}_d`)}</p></div>)}</div></section>
<section className="testimonials"><div className="section-head reveal"><p className="kicker">{t("test_kicker")}</p><h2>{t("test_title")}</h2></div><div className="testi-grid">{[1,2,3].map(n=><figure className="testi reveal" key={n}><blockquote>{t(`ts${n}_q`)}</blockquote><figcaption><strong>{t(`ts${n}_n`)}</strong><span>{t(`ts${n}_l`)}</span></figcaption></figure>)}</div></section>
<section className="faq" id="faq"><div className="section-head reveal"><p className="kicker">{t("faq_kicker")}</p><h2>{t("faq_title")}</h2></div><div className="faq-list reveal">{[1,2,3,4,5,6].map(n=><details className="faq-item" key={n}><summary>{t(`fq${n}_q`)}</summary><p>{t(`fq${n}_a`)}</p></details>)}</div></section>
<section className="cta" id="enroll"><div className="cta-inner reveal"><h2>{t("cta_title")}</h2><p>{t("cta_sub")}</p><div className="hero-ctas"><a href="https://wa.me/923014592661" className="btn btn-light">{t("cta_btn")}</a><a href="mailto:info@markazalimurtaza.com" className="btn btn-outline-light">{t("nav_contact")}</a></div></div></section>
</main><Footer/></>}
