import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer, Header } from "@/components/SiteChrome";
import { HADITH_BOOKS, HADITH_LANGUAGES, isHadithLanguage } from "@/lib/hadith";
import { getAdjacentHadith, getHadith } from "@/lib/hadith-repository";
import { getTranslation } from "@/lib/translation-server";
import { I18N } from "@/lib/i18n";
import { seoLabel } from "@/lib/ui-language";

export const revalidate=86400;
type Params=Promise<{lang:string;book:string;number:string}>;
async function resolve(params:Params){const {lang,book:slug,number:raw}=await params;if(!isHadithLanguage(lang))return null;const book=HADITH_BOOKS.find(b=>b.slug===slug);const number=Number(raw);if(!book||!Number.isInteger(number))return null;const record=await getHadith(slug,number);if(!record)return null;const translation=lang==="ar"?{text:record.hadith.arabic,provider:"source" as const,cached:true}:await getTranslation(record.hadith.id,record.hadith.english.text,lang);return {lang,book,number,...record,translation}}
export async function generateMetadata({params}:{params:Params}):Promise<Metadata>{const item=await resolve(params);if(!item)return {title:"Hadith not found",robots:{index:false}};const {lang,book,number,translation}=item;const title=`${book.english} ${number} — ${I18N[lang].name} | Markaz ul Murtaza (may Allah be pleased with him)`;const description=translation.text.replace(/\s+/g," ").slice(0,155);const path=`/${lang}/hadith/${book.slug}/${number}`;const languages=Object.fromEntries(HADITH_LANGUAGES.map(code=>[code,`/${code}/hadith/${book.slug}/${number}`]));return {title,description,alternates:{canonical:path,languages},robots:{index:translation.provider!=="fallback",follow:true},openGraph:{type:"article",title,description,url:path,locale:lang},twitter:{card:"summary",title,description}}}
export default async function LanguageHadithPage({params}:{params:Params}){const item=await resolve(params);if(!item)notFound();const {lang,book,number,hadith,chapter,translation}=item;const adjacent=await getAdjacentHadith(book.slug,number);const canonical=`https://markazalimurtaza.com/${lang}/hadith/${book.slug}/${number}`;const schema={"@context":"https://schema.org","@type":"Article",headline:`${book.english} ${number}`,description:translation.text.slice(0,200),url:canonical,inLanguage:lang,isPartOf:{"@type":"Book",name:book.english,alternateName:book.arabic},publisher:{"@type":"EducationalOrganization",name:"Markaz ul Murtaza (may Allah be pleased with him)",url:"https://markazalimurtaza.com"},articleBody:`${hadith.arabic}\n\n${translation.text}`};const rtl=I18N[lang].rtl;return <><Header dark active="hadith" languageCodes={HADITH_LANGUAGES} forcedLanguage={lang}/><main className="seo-hadith-page"><nav className="breadcrumbs"><Link href="/">{seoLabel(lang,"home")}</Link><span>›</span><Link href="/hadith">{seoLabel(lang,"library")}</Link><span>›</span><span>{book.english} {number}</span></nav><article className="seo-hadith" lang={lang} dir={rtl?"rtl":"ltr"}><header><p className="kicker">{lang==="ar"?(chapter?.arabic||book.arabic):(chapter?.english||book.english)}</p><h1>{book.english} {number}</h1><p className="book-ar" lang="ar" dir="rtl">{book.arabic}{chapter?.arabic?` — ${chapter.arabic}`:""}</p></header>{hadith.english.narrator&&<p className="had-narr">{hadith.english.narrator}</p>}<p className="had-ar" lang="ar" dir="rtl">{hadith.arabic}</p><section className="seo-english"><h2>{seoLabel(lang,"translation")}</h2><p lang={lang} dir={rtl?"rtl":"ltr"}>{translation.text}</p><p className="had-tr-meta">{translation.provider==="source"?seoLabel(lang,"source"):translation.provider==="fallback"?seoLabel(lang,"fallback"):`${seoLabel(lang,"machine")} · ${translation.provider}`}</p></section><nav className="language-versions" aria-label="Available translations">{HADITH_LANGUAGES.map(code=><Link key={code} href={`/${code}/hadith/${book.slug}/${number}`} hrefLang={code} className={code===lang?"active":""}>{I18N[code].flag} {I18N[code].name}</Link>)}</nav><nav className="hadith-prev-next">{adjacent.previous?<Link href={`/${lang}/hadith/${book.slug}/${adjacent.previous}`}>‹ {seoLabel(lang,"previous")} · {book.english} {adjacent.previous}</Link>:<span/>}{adjacent.next&&<Link href={`/${lang}/hadith/${book.slug}/${adjacent.next}`}>{seoLabel(lang,"next")} · {book.english} {adjacent.next} ›</Link>}</nav></article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main><Footer forcedLanguage={lang}/></>}
