import React,{useEffect,useMemo,useState} from 'react';

const BRAND='Markaz Al Murtaza Al Islami & Safia Islamic Institute';
const WA='https://wa.me/923014592661?text='+encodeURIComponent(`Assalamu alaikum, I would like to enroll at ${BRAND}.`);
const languages=[['en','🌍','English'],['ar','🇸🇦','العربية'],['ur','🇵🇰','اردو'],['fa','🇮🇷','فارسی'],['ps','🇦🇫','پښتو'],['sd','🇵🇰','سنڌي'],['ks','🏔️','کٲشُر'],['pa','🇵🇰','ਪੰਜਾਬੀ'],['tr','🇹🇷','Türkçe'],['az','🇦🇿','Azərbaycan dili'],['kk','🇰🇿','Қазақ тілі'],['uz','🇺🇿','Oʻzbekcha'],['id','🇮🇩','Bahasa Indonesia'],['ms','🇲🇾','Bahasa Melayu'],['bn','🇧🇩','বাংলা'],['hi','🇮🇳','हिन्दी'],['ta','🇱🇰','தமிழ்'],['so','🇸🇴','Soomaali'],['sw','🇰🇪','Kiswahili'],['ha','🇳🇬','Hausa'],['am','🇪🇹','አማርኛ'],['fr','🇫🇷','Français'],['es','🇪🇸','Español'],['de','🇩🇪','Deutsch'],['it','🇮🇹','Italiano'],['pt','🇧🇷','Português'],['ru','🇷🇺','Русский'],['zh','🇨🇳','中文'],['ja','🇯🇵','日本語'],['ko','🇰🇷','한국어']];
const copy={
 en:{brand:BRAND,programs:'Programs',teachers:'Teachers',about:'Why us',donate:'Donate',enroll:'Enroll now',badge:'Online Quran Institute · Pakistan · Worldwide',hero:'Learn the Quran with personal guidance.',sub:'One-to-one online classes in Hifz, Nazra and Tajweed for children and adults.',trial:'Start a free trial',explore:'Explore programs',mission:'Where a noble intention becomes a lived practice.',missionText:'We guide learners from uncertainty to confident recitation through patient teaching, practical Tajweed and a dependable routine for Nazra and Hifz.',programTitle:'A complete Quran education.',why:'Learning designed around the student.',contact:'Contact on WhatsApp'},
 ur:{brand:'مرکز المرتضٰی الاسلامی و صفیہ اسلامک انسٹیٹیوٹ',programs:'پروگرام',teachers:'اساتذہ',about:'ہم کیوں',donate:'عطیہ',enroll:'داخلہ لیں',badge:'آن لائن قرآنی ادارہ · پاکستان · دنیا بھر',hero:'انفرادی رہنمائی کے ساتھ قرآن سیکھیں۔',sub:'بچوں اور بڑوں کے لیے حفظ، ناظرہ اور تجوید کی ون آن ون آن لائن کلاسیں۔',trial:'مفت ٹرائل شروع کریں',explore:'پروگرام دیکھیں',mission:'جہاں نیک ارادہ عملی سفر بنتا ہے۔',missionText:'ہم صبر کے ساتھ تدریس، عملی تجوید اور حفظ و ناظرہ کے قابلِ اعتماد معمول سے طلبہ کو پُراعتماد تلاوت تک پہنچاتے ہیں۔',programTitle:'مکمل قرآنی تعلیم۔',why:'ہر طالب علم کے مطابق تعلیم۔',contact:'واٹس ایپ پر رابطہ'},
 ar:{brand:'مرکز المرتضٰی الاسلامی و صفیہ اسلامک انسٹیٹیوٹ',programs:'البرامج',teachers:'المعلمون',about:'لماذا نحن',donate:'تبرع',enroll:'سجّل الآن',badge:'معهد قرآني إلكتروني · باكستان · للعالم',hero:'تعلّم القرآن بإرشاد شخصي.',sub:'دروس فردية مباشرة في الحفظ والناظرة والتجويد للأطفال والكبار.',trial:'ابدأ تجربة مجانية',explore:'استكشف البرامج',mission:'حيث تتحول النية النبيلة إلى ممارسة.',missionText:'نقود المتعلم من التردد إلى التلاوة الواثقة بالتعليم الصبور والتجويد العملي وخطة ثابتة للحفظ والناظرة.',programTitle:'تعليم قرآني متكامل.',why:'تعليم مصمم حول الطالب.',contact:'تواصل عبر واتساب'}
};
const programs={
 hifz:{name:'Online Hifz Classes',ar:'حِفْظُ الْقُرْآنِ',intro:'Memorize the Quran through a personal Sabaq, Sabqi and Manzil plan.',items:['Personal memorization targets','Daily recent and older revision','Direct recitation correction','Progress suited to your pace']},
 tajweed:{name:'Online Tajweed Classes',ar:'تَجْوِيدُ الْقُرْآنِ',intro:'Improve Makharij, Sifat and practical recitation with individual correction.',items:['Makharij al-Huruf','Essential Sifat','Madd, Ghunnah, Idgham and Ikhfa','Fluency and confidence']},
 nazra:{name:'Online Nazra Quran Classes',ar:'تِلَاوَةُ الْقُرْآنِ نَظَرًا',intro:'Build accurate Quran reading from Noorani Qaida foundations to fluency.',items:['Arabic letter recognition','Vowel marks and joining','Guided daily recitation','Patient one-to-one correction']}
};
const account=[['Meezan Bank','Muhammad Ahmed','PK18 MEZN 0002 3101 0568 3270'],['JazzCash','Markaz ul huda','PK37 JCMA 2606 9234 8659 6339']];
function route(){const h=location.hash;return h.startsWith('#/')?h.slice(2).split('?')[0]:'home'}
function Nav({t,lang,setLang}){const [open,setOpen]=useState(false);return <header className="nav"><a className="brand" href="#/"><img src="/images/institute-logo.png"/><span>{t.brand}</span></a><nav className={open?'open':''}><a href="#programs">{t.programs}</a><a href="#teachers">{t.teachers}</a><a href="#features">{t.about}</a><a href="#/portfolio">Portfolio</a><a href="#/donate">{t.donate}</a></nav><div className="actions"><select value={lang} onChange={e=>setLang(e.target.value)} aria-label="Language">{languages.map(x=><option value={x[0]} key={x[0]}>{x[1]} {x[2]}</option>)}</select><a className="btn small" href={WA}>{t.enroll}</a><button className="menu" onClick={()=>setOpen(!open)}>☰</button></div></header>}
function Footer({t}){return <footer><div><div className="footbrand"><img src="/images/institute-logo.png"/><strong>{t.brand}</strong></div><p>One-to-one Hifz, Nazra and Tajweed classes for learners worldwide.</p></div><div><h4>Programs</h4><a href="#/hifz">Hifz</a><a href="#/tajweed">Tajweed</a><a href="#/nazra">Nazra</a></div><div><h4>Institute</h4><a href="#/portfolio">Teacher portfolio</a><a href="#/online-quran-classes">Online Quran classes</a><a href="#/donate">Donate</a></div><div><h4>Contact</h4><a href="tel:+923014592661">+92 301 4592661</a><a href={WA}>WhatsApp</a></div></footer>}
function Home({t}){return <main><section className="hero"><p className="eyebrow">{t.badge}</p><h1>{t.hero}</h1><p>{t.sub}</p><div><a className="btn" href={WA}>{t.trial}</a><a className="btn ghost" href="#programs">{t.explore}</a></div></section><section className="gallery"><header><p className="kicker">Our learning home</p><h2>A place shaped around the Quran.</h2></header>{[['front','Rooted in a real learning space','A purpose-built identity for focused Quran education.'],['entrance','An entrance to lifelong learning','A welcoming environment representing discipline and care.'],['community','Tradition carried beyond walls','Personal Hifz, Nazra and Tajweed learning, wherever you live.']].map((x,i)=><figure className={i===0?'wide':''} key={x[0]}><img src={`/images/institute-wide-${x[0]}.webp`}/><figcaption><h3>{x[1]}</h3><p>{x[2]}</p></figcaption></figure>)}</section><section className="mission"><div><p className="kicker">Quran and Sunnah</p><h2>{t.mission}</h2></div><div><p>{t.missionText}</p><p>With 16 years of experience, the mission is expanding from an Urdu-speaking community to families worldwide, by the mercy and help of Allah.</p></div></section><section id="programs"><header><p className="kicker">{t.programs}</p><h2>{t.programTitle}</h2></header><div className="cards">{Object.entries(programs).map(([k,p])=><a className="card" href={`#/${k}`} key={k}><span lang="ar">{p.ar}</span><h3>{p.name}</h3><p>{p.intro}</p><b>Explore →</b></a>)}</div></section><section id="teachers" className="teachers"><header><p className="kicker">Teaching leadership</p><h2>Learn with personal guidance.</h2></header><div className="teacher"><img src="/images/qari-azizi-thumb.jpg"/><div><h3>Qari Ahmed Azizi</h3><p>Head of the Institution</p><p>Mudir (Principal), Jamia Riaz-ul-Jannah, Allama Iqbal Town, Lahore</p><a className="btn" href={WA}>WhatsApp</a></div></div></section><section className="stats"><div><b>1.2K+</b><span>Students enrolled</span></div><div><b>2</b><span>Countries served</span></div><div><b>500+</b><span>Certified students</span></div><div><b>16</b><span>Years of experience</span></div></section><section id="features"><header><p className="kicker">Why choose us</p><h2>{t.why}</h2></header><div className="cards">{[['One-to-one classes','Direct teacher attention at your own pace.'],['Flexible scheduling','Choose a suitable time across time zones.'],['Free assessment','Begin with a trial and a clear starting level.']].map(x=><article className="card" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section><section className="cta"><h2>Begin your Quran journey.</h2><p>Discuss your level, program and preferred schedule.</p><a className="btn" href={WA}>{t.contact}</a></section></main>}
function Program({kind}){const p=programs[kind];return <main><section className={`pagehero ${kind}`}><p lang="ar">{p.ar}</p><h1>{p.name}</h1><p>{p.intro}</p><a className="btn light" href={WA}>Start a free trial</a></section><section className="detail"><div><p className="kicker">Program overview</p><h2>Learn with personal guidance.</h2><p>{p.intro} Every lesson gives the student a focused plan and direct correction.</p><ul>{p.items.map(x=><li key={x}>✓ {x}</li>)}</ul></div><aside><b>One-to-one live online classes</b><span>For children and adults</span><a className="btn" href={WA}>Contact the institute</a></aside></section></main>}
function Portfolio(){return <main><section className="subhero"><p className="kicker">Our teaching leadership</p><h1>Teachers, roles and experience.</h1></section><section className="profiles"><article><img src="/images/qari-azizi-thumb.jpg"/><div><h2>Qari Ahmed Azizi</h2><ul><li>Head of Markaz Al Murtaza Al Islami & Safia Islamic Institute</li><li>Mudir (Principal), Jamia Riaz-ul-Jannah, Allama Iqbal Town, Lahore</li><li>Quran reciter and teacher with publicly available recitation work</li></ul><a className="btn" href={WA}>WhatsApp</a></div></article><article><img src="/images/qari-abdurrahman-thumb.jpg"/><div><h2>Qari Abdur Rahman Al Afin</h2><ul><li>Qari and Quran instructor</li><li>Quran reciter with publicly available video recitation</li></ul><a className="btn" href="https://wa.me/923168724692">WhatsApp</a></div></article></section></main>}
function Donate(){const copy=v=>navigator.clipboard?.writeText(v);return <main><section className="subhero"><p className="kicker">Sadaqah Jariyah</p><h1>Support Quran learning.</h1></section><section className="donate"><h2>Donation details</h2>{account.map(a=><article key={a[2]}><p><span>Bank / Wallet</span><b>{a[0]}</b></p><p><span>Account name</span><b>{a[1]}</b></p><p><span>IBAN</span><b dir="ltr">{a[2]}</b></p><button onClick={()=>copy(a.join('\n'))}>Copy details</button></article>)}<a className="btn" href={WA}>Confirm via WhatsApp</a></section></main>}
function SearchLanding({combined=false}){return <main><section className="subhero"><p className="kicker">One-to-one live learning</p><h1>{combined?'Online Hifz and Tajweed Institute':'Online Quran Classes for Kids and Adults'}</h1><p>{combined?'Structured memorization, revision and practical Tajweed correction.':'Personal Hifz, Nazra and Tajweed lessons with flexible scheduling.'}</p><a className="btn light" href={WA}>Book a free trial</a></section><section><header><p className="kicker">Find the right Quran teacher online</p><h2>A focused path, wherever you live.</h2></header><div className="cards">{Object.entries(programs).map(([k,p])=><a className="card" href={`#/${k}`} key={k}><h3>{p.name}</h3><p>{p.intro}</p></a>)}</div></section></main>}
function Jamia(){return <main><section className="subhero"><p className="kicker">Quran teaching leadership in Lahore</p><h1>Qari Ahmed Azizi and Jamia Riaz-ul-Jannah</h1></section><section className="teacher jamia"><img src="/images/qari-azizi-thumb.jpg"/><div><h2>Qari Ahmed Azizi</h2><p>Qari Ahmed Azizi serves as Mudir (Principal) of Jamia Riaz-ul-Jannah in Allama Iqbal Town, Lahore. He also leads the online Quran programs of Markaz Al Murtaza Al Islami & Safia Islamic Institute.</p><a className="btn" href={WA}>Contact on WhatsApp</a></div></section></main>}
export default function App(){const [lang,setLang]=useState(localStorage.getItem('markaz_lang')||'en');const [page,setPage]=useState(route());useEffect(()=>{const f=()=>{setPage(route());scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);useEffect(()=>{localStorage.setItem('markaz_lang',lang);document.documentElement.lang=lang;document.documentElement.dir=['ar','ur','fa','ps','sd','ks'].includes(lang)?'rtl':'ltr'},[lang]);const t=useMemo(()=>copy[lang]||copy.en,[lang]);let content=page==='home'?<Home t={t}/>:programs[page]?<Program kind={page}/>:page==='portfolio'?<Portfolio/>:page==='donate'?<Donate/>:page==='online-quran-classes'?<SearchLanding/>:page==='online-hifz-tajweed-institute'?<SearchLanding combined/>:page==='jamia-riaz-ul-jannah'?<Jamia/>:<Home t={t}/>;return <><Nav t={t} lang={lang} setLang={setLang}/>{content}<Footer t={t}/></>}
